spring.application.name=car-service

# Indirizzo del DB (localhost perché il container espone la porta 5432 sul tuo PC)
# spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
# spring.datasource.username=postgres
# spring.datasource.password=poppapoppo123


# Se Spring trova una variabile d'ambiente 'DB_URL', usa quella. 
# Altrimenti usa localhost (quello che hai ora).
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:poppapoppo123}

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate: crea le tabelle in automatico basandosi sulle tue classi Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cambia il percorso della documentazione (opzionale)
springdoc.swagger-ui.path=/swagger-ui.html
# Ordina gli endpoint alfabeticamente
springdoc.swagger-ui.operationsSorter=alpha

# Logging
logging.file.name=logs/car-service.log
logging.level.com.example.car_service=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] [%X{x-Request-ID}] %logger{36} : %m%n


# Frequenza del monitoraggio (in millisecondi)
maintenance.monitor.rate=30000
maintenance.monitor.enabled=${MONITOR_ENABLED:true}

# Configurazione Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=af7c7234b7a70c
spring.mail.password=f13da6cf0e9c0e
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



# In locale di default è true, ma in produzione è false e puoi abilitarlo con una variabile d'ambiente
maintenance.email.enabled=${EMAIL_ENABLED:true}

# 5 minuti in millisecondi
maintenance.email.rate=300000